### ISSUE TITLE
README.md says Java 11 is needed. Compilation fails with Java 11

### ISSUE THREAD

**Issue by csdivi** [vmware/connectors-workspace-one#156]
README.md says Java 11 is needed. Compilation fails with Java 11.

The file pom.xml has source and target dependencies mentioned as 12.

**Comment by RyanBard** [comment]
Thanks for reporting it.  We'll get it updated and steps reverified soon.

**Comment by RyanBard** [comment]
Readme updated:
* https://github.com/vmware/connectors-workspace-one/commit/0075a53013fadf05fe0caf02535b016b883e2ab0
